dependencies:
- name: bdd-gh-1571069793
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-ghfjxy-import-1571071347
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-nh-1571069793
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-nh-import-1571071347
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-sbhg-1571069793
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-sbhg-import-1571071347
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-sbrp-import-1571071347
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-spring-1571068903
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.112
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.112
